### ISSUE TITLE
Keyboard Shortcuts Don't Work

### ISSUE THREAD

**Issue by ianizaguirre** [Devine-Davies/vs-make-hidden#13]
For Example, If I try to assign a keyboard shortcut to the "hide" command, I get:

`Running the contributed command:'make-hidden.hideItem' failed.`

How can I get this to work, so I don't have to right click to find the "hide" name in the menu, every time I want to hide a file?

**Comment by startswithaj** [comment]
Hi @Devine-Davies - thanks very much for making this extension. I've been using it for ages now and it helps my workflow heaps. I'd like to be able to assign a keyboard shortcut to hide. If you point me in the right direction I would be happy to try implement for you and push up a pr :)

**Comment by Devine-Davies** [comment]
Hi there and thanks for the support and comments. Sorry, it has taken a while to get around to answer these.

I thought about your query and not 100% sure on how this will be implemented. The issue comes as when right-clicking on an item within the view pane and selecting Hide from the context menu, we are able to retrieve the name/path of that item to target and hide.

I could implement a feature that show the directory layout in a vs code dialog when a key combo has been pressed, allowing items to be selected, but this it out of scope for the time being.

Happy Coding.
