### ISSUE TITLE
Hidden items sidebar is empty

### ISSUE THREAD

**Issue by ianizaguirre** [Devine-Davies/vs-make-hidden#17]
The sidebar is supposed to list my hidden items but even though my items are hidden they don't appear listed here anymore. It stopped working for me.

**Comment by TMPxyz** [comment]
Yeah, same here.

It worked well the first time I installed here, and after I uninstalled and reinstalled it, the sidebar becomes empty and no workspace can be created.

**Comment by Devine-Davies** [comment]
Hi and thank you for reporting.

If you wouldn't mind listing your operating system, vs code and the make-hidden versions along with steps in order to reproduce the problem. I'd be happy to try and do some debugging.

If you could also provide me with a  copy of the Make Hidden JSON file that is created by the extension could also be useful. Usually located at:
"/Users/{you}/Library/Application\ Support/Code/User/MakeHidden.json " on mac

Thanks again.

**Comment by TMPxyz** [comment]
Hi, 

I'm using vscode 1.35.0 and MarkHidden 3.0.3 on Win10.

As for the repo steps, I cannot remember the steps the first time I installed. As for now, it stays this way and re-install doesn't solve it at all.

Could you also post the path of "MarkHidden.json" on windows machine? 

Regards,

**Comment by ianizaguirre** [comment]
@Devine-Davies I am on a Macbook pro / macOS High Sierra Version 10.13.6.

My vs-code is `Code '1.26.0'.` 


`"/Users/{you}/Library/Application\ Support/Code/User/MakeHidden.json "` -> I opened this file and it was an empty file with just an empty array in it: `[]`.

makeHidden is on 3.0.3

**Comment by Devine-Davies** [comment]
Hi and cheers for sharing.

I have tested the extensions across Windows and Mac and all looks good.

When right-clicking and selecting "Hide" on an item within the directory, does this hide that item? The extension might be having trouble writing to the file '.vscode/settings.js' due to permissions. Double check that you are able to read & write to that file.

Regards.
